# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: badef38e0dd0c40feae5ace9534eb7221ed7e4ab33af9e2b33712aa860ee91846ddf729d4e2ca01af5ae9e03d966958433c2325b2135e7e3dda202b163bd9bcd

test:
  secret_key_base: 5a531a92f02574a51dee05051b372bead5a4acf0812518f9868751632747c1de4f77bf83004a5aa6a8082c40bc1a671312adbff6f1ca6cc9c8553a35ca350d70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
